### ISSUE TITLE
Felmeddelande vid kompilering

### ISSUE THREAD

**Issue by Joyje** [Joyje/electrotest#1]
Den här raden:

https://github.com/Joyje/electrotest/blob/98e2aa81a502f42ddde18dc888255ca7cfe1f313/src/lib/component/libcomponent.c#L123

ger ett felmeddelande vid kompileringen. Programmet fungerar trots allt så det är kanske inte jättehög prio att fixa, men en kod som kompileras utan felmeddelanden är att föredra.

**Comment by l82** [comment]
Hej,
Absolut ska det fixas! Tack! Märkligt bara att jag försökte slå på att den skulle faila kompileringen även vid varningar... ;-()
Mvh
L8

Skickat från min iPhone

**Comment by l82** [comment]
Det var en intialiserings bug! Tack! Nu fixat.
